# Generated by Django 2.2.17 on 2020-12-07 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='path',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='painting',
            name='path',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
