# Generated by Django 2.2.17 on 2020-12-07 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_auto_20201208_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/'),
        ),
        migrations.AlterField(
            model_name='painting',
            name='painting',
            field=models.ImageField(blank=True, null=True, upload_to='static/'),
        ),
    ]
