# Generated by Django 3.1.4 on 2020-12-25 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_auto_20201208_0110'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Word',
        ),
    ]
