# Generated by Django 3.1 on 2020-12-15 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstScreen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='text',
            field=models.TextField(default='デフォルトのメッセージ', max_length=16),
        ),
    ]
