# Generated by Django 3.1 on 2020-12-15 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstScreen', '0002_auto_20201215_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='painting_name',
            field=models.CharField(default='0_coverpage.png', max_length=20),
        ),
    ]
