# Generated by Django 3.1 on 2020-12-15 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstScreen', '0003_member_painting_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='ballon_type',
            field=models.CharField(choices=[('1', '左下'), ('2', '左上'), ('3', '右下'), ('4', '右下')], default='1', max_length=1),
        ),
    ]
