# Generated by Django 3.1 on 2021-01-11 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstScreen', '0004_auto_20201216_0553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='ballon_height',
        ),
        migrations.RemoveField(
            model_name='member',
            name='ballon_wight',
        ),
        migrations.RemoveField(
            model_name='member',
            name='painting_name',
        ),
    ]
