# Generated by Django 3.1 on 2021-01-11 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstScreen', '0007_member_font_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='font_size',
            field=models.CharField(choices=[('1', '大'), ('2', '中'), ('3', '小')], default='2', max_length=1),
        ),
    ]
